name       : python-pulsectl
version    : 20.5.1
release    : 3
source     :
    - https://pypi.io/packages/source/p/pulsectl/pulsectl-20.5.1.tar.gz : 39b0a0e7974a7d6468d826a838822f78b00ac9c3803f0d7bfa9b1cad08ee22db
license    : MIT
component  : programming.python
summary    : High-level interface and ctypes-based bindings for PulseAudio
description: |
    Python high-level interface and ctypes-based bindings for PulseAudio (libpulse), mostly focused on mixer-like controls and introspection-related operations (as opposed to e.g. submitting sound samples to play, player-like client).
rundeps    :
    - pulseaudio
build      : |
    %python3_setup
install    : |
    %python3_install
