name       : python-pulsectl
version    : 18.12.5
release    : 2
source     :
    - https://files.pythonhosted.org/packages/1a/a9/cdd1a19889f78ddd45775b9830045df2b4eb25f63911a2ddc3aaf8ec614f/pulsectl-18.12.5.tar.gz : 41db4dd19e7cd28e2609baf2b551f34991f1890024be119b6075a286abfb65d3
license    : MIT
component  : programming.python
summary    : High-level interface and ctypes-based bindings for PulseAudio
description: |
    Python high-level interface and ctypes-based bindings for PulseAudio (libpulse), mostly focused on mixer-like controls and introspection-related operations (as opposed to e.g. submitting sound samples to play, player-like client).
rundeps    :
    - pulseaudio
build      : |
    %python3_setup
install    : |
    %python3_install
